lib/phello_web/router.ex
defmodule PhelloWeb.Router do
  use PhelloWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhelloWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BoardController, :index
    resources "/boards", BoardController do
      resources "/cards", CardController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Phello do
  #   pipe_through :api
  # end
end

lib/phello/application.ex
defmodule Phello.Application do
  use Application

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Phello.Repo, []),
      # Start the endpoint when the application starts
      supervisor(PhelloWeb.Endpoint, []),
      # Start your own worker by calling: Phello.Worker.start_link(arg1, arg2, arg3)
      # worker(Phello.Worker, [arg1, arg2, arg3]),
    ]

    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Phello.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration            
  # whenever the application is updated.            
  def config_change(changed, _new, removed) do            
    PhelloWeb.Endpoint.config_change(changed, removed)            
    :ok            
  end
end

lib/phello/repo.ex
defmodule Phello.Repo do
  use Ecto.Repo, otp_app: :phello

  @doc """            
  Dynamically loads the repository url from the            
  DATABASE_URL environment variable.            
  """            
  def init(_, opts) do            
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}            
  end
end

lib/phello/tracking/board.ex
defmodule Phello.Tracking.Board do
  use Phello.Schema
  import Ecto.Changeset

  schema "boards" do
    field :name, :string

    has_many :cards, Phello.Tracking.Card
    timestamps()
  end

  def changeset(%Phello.Tracking.Board{} = board, attrs) do
    board
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/phello/tracking/card.ex
defmodule Phello.Tracking.Card do
  use Phello.Schema

  schema "cards" do
    field :name, :string
    field :description, :string
    belongs_to :board, Phello.Tracking.Board

    timestamps()
  end

  def changeset(%Phello.Tracking.Card{} = card, attrs) do
    card
    |> cast(attrs, [:name, :description, :board_id])
    |> validate_required([:name, :description, :board_id])
  end
end

lib/phello/tracking/tracking.ex
defmodule Phello.Tracking do
  @moduledoc """
  The boundary for the Tracking system.
  """

  import Ecto.{Query, Changeset}, warn: false
  alias Phello.Repo

  alias Phello.Tracking.Board

  def list_boards do
    Repo.all(Board)
  end

  def get_board!(id) do
    Repo.get!(Board, id)
    |> Repo.preload([:cards])
  end

  def create_board(attrs \\ %{}) do
    %Board{}
    |> change_board(attrs)
    |> Repo.insert()
  end

  def update_board(id, attrs \\ %{}) do
    board = get_board!(id)
    change_board(board, attrs)
    |> Repo.update()
  end

  def delete_board!(id) do
    get_board!(id)
    |> Repo.delete
  end

  def change_board(%Board{} = board, attrs) do
    Board.changeset(board, attrs)
  end

  alias Phello.Tracking.Card

  def list_cards do
    Repo.all(Card)
  end

  def get_card!(id), do: Repo.get!(Card, id)

  def create_card(attrs \\ %{}) do
    %Card{}
    |> change_card(attrs)
    |> Repo.insert()
  end

  def update_card(id, attrs \\ %{}) do
    card = get_card!(id)
    change_card(card, attrs)
    |> Repo.update()
  end

  def delete_card!(id) do
    get_card!(id)
    |> Repo.delete()
  end

  def change_card(%Card{} = card, attrs) do
    Card.changeset(card, attrs)
  end
end

lib/phello_web/controllers/board_controller.ex
defmodule PhelloWeb.BoardController do
  use PhelloWeb, :controller

  alias Phello.Tracking
  alias Phello.Tracking.Board

  def index(conn, _params) do
    boards = Tracking.list_boards()
    render(conn, "index.html", boards: boards)
  end

  def new(conn, _params) do
    changeset = Tracking.change_board(%Board{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"board" => board_params}) do
    case Tracking.create_board(board_params) do
      {:ok, board} ->
        conn
        |> put_flash(:info, "Board created successfully.")
        |> redirect(to: board_path(conn, :show, board))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    board = Tracking.get_board!(id)
    render(conn, "show.html", board: board)
  end

  def edit(conn, %{"id" => id}) do
    board = Tracking.get_board!(id)
    changeset = Tracking.change_board(board, %{})
    render(conn, "edit.html", board: board, changeset: changeset)
  end

  def update(conn, %{"id" => id, "board" => board_params}) do

    #TODO
    board = Tracking.get_board!(id)
    case Tracking.update_board(id, board_params) do
      {:ok, board} ->
        conn
        |> put_flash(:info, "Board updated successfully.")
        |> redirect(to: board_path(conn, :show, board))
      {:error, changeset} ->
        render(conn, "edit.html", board: board, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    Tracking.delete_board!(id)

    conn
    |> put_flash(:info, "Board deleted successfully.")
    |> redirect(to: board_path(conn, :index))
  end
end

lib/phello_web/controllers/card_controller.ex
defmodule PhelloWeb.CardController do
  use PhelloWeb, :controller

  alias Phello.Tracking
  alias Phello.Tracking.Card

  def index(conn, _params) do
    cards = Tracking.list_cards()
    render(conn, "index.html", cards: cards)
  end

  def new(conn, params) do
    board_id = params["board_id"]
    changeset = Tracking.change_card(%Card{}, %{board_id: board_id})
    render(conn, "new.html", changeset: changeset, board_id: board_id)
  end

  def create(conn, %{"card" => card_params}) do
    case Tracking.create_card(card_params) do
      {:ok, card} ->
        conn
        |> put_flash(:info, "Card created successfully.")
        |> redirect(to: board_path(conn, :show, card.board_id))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, board_id: card_params["board_id"])
    end
  end

  def show(conn, %{"id" => id}) do
    card = Tracking.get_card!(id)
    render(conn, "show.html", card: card)
  end

  def edit(conn, %{"id" => id}) do
    card = Tracking.get_card!(id)
    changeset = Tracking.change_card(card, %{})
    render(conn, "edit.html", card: card, changeset: changeset)
  end

  def update(conn, %{"id" => id, "card" => card_params}) do
    card = Tracking.get_card!(id)

    case Tracking.update_card(card_params) do
      {:ok, card} ->
        conn
        |> put_flash(:info, "Card updated successfully.")
        |> redirect(to: board_path(conn, :show, card.board_id))
      {:error, changeset} ->
        render(conn, "edit.html", card: card, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id, "board_id" => board_id}) do
    Tracking.delete_card!(id)

    conn
    |> put_flash(:info, "Card deleted successfully.")
    |> redirect(to: board_path(conn, :index, board_id))
  end
end

lib/phello_web/views/board_view.ex
defmodule PhelloWeb.BoardView do
  use PhelloWeb, :view
end

lib/phello_web/views/card_view.ex
defmodule PhelloWeb.CardView do
  use PhelloWeb, :view
end

lib/phello_web/views/error_view.ex
defmodule PhelloWeb.ErrorView do
  use PhelloWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/phello_web/views/layout_view.ex
defmodule PhelloWeb.LayoutView do
  use PhelloWeb, :view
end

lib/phello_web/templates/board/edit.html.eex
<h2>Edit board</h2>

<%= render "form.html", changeset: @changeset,
                        action: board_path(@conn, :update, @board) %>

<%= link "Back", to: board_path(@conn, :index) %>

lib/phello_web/templates/board/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/phello_web/templates/board/index.html.eex
<h2>Listing boards</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for board <- @boards do %>
    <tr>
      <td><%= board.name %></td>

      <td class="text-right">
        <%= link "Show", to: board_path(@conn, :show, board), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: board_path(@conn, :edit, board), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: board_path(@conn, :delete, board), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New board", to: board_path(@conn, :new) %>

lib/phello_web/templates/board/new.html.eex
<h2>New board</h2>

<%= render "form.html", changeset: @changeset,
                        action: board_path(@conn, :create) %>

<%= link "Back", to: board_path(@conn, :index) %>

lib/phello_web/templates/board/show.html.eex
<h2>Show board</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @board.name %>
  </li>
</ul>
<ul>
<%= for card <- @board.cards do %>
  <h2>
    <%= card.name %>
  </h2>
  <p>
    <%= card.description %>
  </p>
<% end %>
</ul>

<%= link "Add card", to: board_card_path(@conn, :new, @board) %>
<br />
<%= link "Edit", to: board_path(@conn, :edit, @board) %>
<br/>
<%= link "Back", to: board_path(@conn, :index) %>

lib/phello_web/templates/card/edit.html.eex
<h2>Edit card</h2>

<%= render "form.html", changeset: @changeset,
                        action: board_card_path(@conn, :update, @card.board_id, @card) %>

<%= link "Back", to: board_path(@conn, :index) %>

lib/phello_web/templates/card/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= text_input f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>
  <%= hidden_input f, :board_id, class: "form-control" %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/phello_web/templates/card/new.html.eex
<h2>New card</h2>

<%= render "form.html", changeset: @changeset,
                        action: board_card_path(@conn, :create, @board_id) %>

<%= link "Back", to: board_path(@conn, :index) %>

lib/phello_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Phello!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>